CONFIG_FILE=../config.mk
include ${CONFIG_FILE}

LIBS=-L/usr/local/lib -L/opt/local/lib -lpthread -ldl  -lutil -lm -lgmp -lpbc
OPTS=-DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

CFLAGS+=${PY_CFLAGS}

LDFLAGS+=${PY_LDFLAGS}
LDFLAGS+=${LIBS}

PROGRAMS=test
OBJECTS=charm_embed_api.o test.o
all: $(PROGRAMS)

test: ${OBJECTS}
	${CC} ${OBJECTS} ${CFLAGS} -no-pie ${LDFLAGS} ${OPTS} -o test

charm_embed_api.o: charm_embed_api.c
	${CC} ${CFLAGS} $(OPTS) -c charm_embed_api.c

charm_embed_api_pic.o: charm_embed_api.c
	${CC} ${CFLAGS} $(OPTS) -fPIC -c charm_embed_api.c -o charm_embed_api_pic.o

libcharm.so: charm_embed_api_pic.o
	${CC} ${CFLAGS} ${LDFLAGS} $(OPTS) -shared -fPIC -Wl,-soname,libcharm.so.1 -o libcharm.so.1.0.0 charm_embed_api_pic.o -lc

libcharm.a: charm_embed_api.o
	ar rcs libcharm.a charm_embed_api.o

test.o: test.c
	${CC} ${CFLAGS} $(OPTS) test.c -c 

clean:
	rm -f $(PROGRAMS) *.o *.pyc core
